### PR TITLE
2nd semester schedule

### PR DESCRIPTION
**Pull request by jshepin**
+Added remote hybrid schedule
+Added hybrid schedule card and logic

Additionally we need to look into the schedule caching issue we discussed earlier. At some point, i'm gonna start running out of names that aren't taken. Thanks - Joseph

https://user-images.githubusercontent.com/31457361/102736624-fc815380-430a-11eb-88d3-b6f38af4767a.mov

### CODE REVIEW

**Comment by apappu9** [comment]
Looks great at first glance!! Will review and also try fixing the caching issue on Tuesday. Thanks!

**Comment by jshepin** [comment]
Great, this should help you in your review. Thanks
image

**Comment by abhinavpappu** [comment]
Ok I had an idea for how best to fix the issue and started implementing it. Main functionality is complete, just need to refactor a couple things and test compatibility. Should be done by tomorrow, and then I'll merge this in

**Comment by abhinavpappu** [comment]
Looks great! Just need to make a few changes to make it compatible with the fix I implemented, so merging it into a different branch for now

**Comment by jshepin** [comment]
are we good to get this merged into `gh-pages`? Thanks

**Comment by abhinavpappu** [comment]
ah sorry, just merged it!

**Comment by abhinavpappu** [comment]
oh also did they give you any info about the half period schedule yet?

**Comment by jshepin** [comment]
Thanks, The school has confirmed that for both the `remote hybrid` and `hybrid` schedule, there are no half periods. They don't want people waiting around in the school (no unused time) and they need to bus people to and from during that time as well. Happy new year!

**Comment by abhinavpappu** [comment]
Sounds good, happy new year to you as well!

One other thing, I noticed that the schedule linked on the school website and the image you commented above look different. Here's the schedule from https://docs.google.com/document/d/165sRjadprXE59ZW8MckV1Q7ZWIT9Ho91KvkQyWZ1sww/edit (the colors and the wednesday schedule are different):
image

It says the google doc was last updated on December 14, has the schedule changed since then?

**Comment by jshepin** [comment]
ah, yes they changed it again. I will work on the change. Thanks for the catch

**Pull request merged**
