### PR TITLE
better half periods

### PR DESCRIPTION
**Pull request by jshepin**
this includes all the half periods

### CODE REVIEW

**Review by abhinavpappu — APPROVED** [review]
Looks good! Only thing I'm wondering is that you used to have 3-4A go until 11:15, but now 4A ends at 11:25

Also, do you think switching 1A/1B and 6A/6B in the half periods schedule would be a good idea? I got this screenshot: 
image
and it might be helpful for periods like 6B-7 but I'm not sure if it would just make things more confusing.

**Comment by jshepin** [comment]
yes about that. It is because of the passing period it ends 10 minutes early, some students wanted all the half periods 1-8 because some people need them for classes and don't want them bridged. I think adding another schedule might be the only option for the bridged periods

**Comment by jshepin** [comment]
actually on second though, I think we should switch those periods to the bridged periods

**Comment by abhinavpappu** [comment]
Would making all the A half periods 10 minutes long work or do some people have a class that ends at 11:25?

**Comment by jshepin** [comment]
I don't think anyone has classes that end at 11:25 because the passing period is 10 minutes making all the 1.5 period classes end at 11:15. So I think that is a good solution

**Comment by jshepin** [comment]
image

**Comment by abhinavpappu** [comment]
Looks good! And did we want to switch the names 1A/1B and 6A/6B?

**Comment by jshepin** [comment]
from everything that I've seen, people are being trained to 1,2,3,4,5,6,7,8 and that they have switched periods, but not the names. Thanks

**Comment by abhinavpappu** [comment]
Ok sounds good, just wanted to make sure it's clear that 6B-7 would now be 1B-7

**Pull request merged**
