### PR TITLE
back to normal schedules

### PR DESCRIPTION
**Pull request by jshepin**
-removed hybrid card
-updated schedules.json
also lunch is unknown at this point. The prebuild script fails because shs has not posted their lunch info back on their site.

### CODE REVIEW

**Comment by jshepin** [comment]
Screen Shot 2021-04-01 at 5 20 45 PM
Screen Shot 2021-04-01 at 5 20 49 PM
Screen Shot 2021-04-01 at 5 20 53 PM

**Comment by jshepin** [comment]
there are two slightly different standard schedules for in person and remote. The reason is for people to clean the room in person, so class starts five minutes earlier. That is the only schedule difference from the original standard schedule.

**Review by abhinavpappu — APPROVED** [review]
Looks great!

About the lunch script, I thought I disabled it until June 1, 2021. Is is the `main` function in `scrapers/lunch.js` still running when you do `npm run build`?

**Comment by jshepin** [comment]
oh yes, you did disable it. What I meant to say was that the endpoint for getting the lunches returns a 404. Once they fix that link, then the lunches should be accurate and we can remove the if statement
https://www.d125.org/students/food-servicelunch-menu/latest-menu.

**Comment by abhinavpappu** [comment]
ohh ok awesome, thanks for letting me know!

**Pull request merged**
